import type { Product } from '@/types/models/Product'
import { TagColor } from '@/types/models/Tag'

export const mockProduct: Product = {
  id: 1,
  name: 'Test Product',
  description: 'This is a test product',
  price: '100.00',
  vatRate: '0.25',
  createdAt: new Date().toISOString(),
  updatedAt: new Date().toISOString(),
  tag: {
    id: 1,
    name: 'Test Tag',
    color: TagColor.Red,
  },
}

export const mockProducts: Product[] = [
  mockProduct,
  {
    id: 2,
    name: 'Another Product',
    description: 'This is another product',
    price: '200.00',
    vatRate: '0.25',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    tag: {
      id: 2,
      name: 'Another Tag',
      color: TagColor.Blue,
    },
  },
  {
    id: 3,
    name: 'Third Product',
    description: 'This is the third product',
    price: '300.00',
    vatRate: '0.25',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 4,
    name: 'Fourth Product',
    description: 'This is the fourth product',
    price: '400.00',
    vatRate: '0.25',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 5,
    name: 'Fifth Product',
    description: 'This is the fifth product',
    price: '500.00',
    vatRate: '0.25',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 6,
    name: 'Sixth Product',
    description: 'This is the sixth product',
    price: '600.00',
    vatRate: '0.25',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 7,
    name: 'Seventh Product',
    description: 'This is the seventh product',
    price: '700.00',
    vatRate: '0.25',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 8,
    name: 'Eighth Product',
    description: 'This is the eighth product',
    price: '800.00',
    vatRate: '0.25',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    tag: {
      id: 3,
      name: 'Other Tag',
      color: TagColor.Orange,
    }
  },
  {
    id: 9,
    name: 'Ninth Product',
    description: 'This is the ninth product',
    price: '900.00',
    vatRate: '0.25',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 10,
    name: 'Tenth Product',
    description: 'This is the tenth product',
    price: '1000.00',
    vatRate: '0.25',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 11,
    name: 'Eleventh Product',
    description: 'This is the eleventh product',
    price: '1100.00',
    vatRate: '0.25',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 12,
    name: 'Twelfth Product',
    description: 'This is the twelfth product',
    price: '1200.00',
    vatRate: '0.25',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 13,
    name: 'Thirteenth Product',
    description: 'This is the thirteenth product',
    price: '1300.00',
    vatRate: '0.25',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 14,
    name: 'Fourteenth Product',
    description: 'This is the fourteenth product',
    price: '1400.00',
    vatRate: '0.25',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 15,
    name: 'Fifteenth Product',
    description: 'This is the fifteenth product',
    price: '1500.00',
    vatRate: '0.25',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  }
]
